AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Anghammarad Lambda and SNS topic

Parameters:
  ArtifactBucket:
    Description: S3 bucket containing the Lambda's artifact
    Type: String
  ArtifactLocation:
    Description: S3 path to the Lambda's artifact
    Type: String
  Stage:
    Description: Application stage (e.g. PROD, CODE)
    Type: String
    AllowedValues:
    - PROD
    - CODE
    - DEV
  AllowedAWSAccountIDs:
    Description: AWS Accounts that are allowed to publish to this topic by default
    Type: List<String>

Mappings:
  Constants:
    Stack:
      Value: deploy
    App:
      Value: anghammarad

Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub anghammarad-${Stage}
      Description: !Sub Process Anghammarad ${Stage} notifications
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - ses:SendEmail
          Resource: "*"
      Handler: com.gu.anghammarad.Main::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          Stage: !Ref Stage
      CodeUri:
        Bucket: !Ref ArtifactBucket
        Key: !Ref ArtifactLocation
      Events:
        Notification:
          Type: SNS
          Properties:
            Topic: !Ref NotificationTopic
      Tags:
        Stack: !FindInMap [ Constants, Stack, Value ]
        App: !FindInMap [ Constants, App, Value ]
        Stage: !Ref Stage

  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub Anghammarad ${Stage} notification topic

  NotificationTopicPolicy:
    Type: "AWS::SNS::TopicPolicy"
    Properties:
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - sns:Publish
          Principal:
            AWS: !Ref AllowedAWSAccountIDs
      Topics:
      - !Ref NotificationTopic

Outputs:
  TopicName:
    Value: !GetAtt NotificationTopic.TopicName
